<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" ignored="0" name="Command line test" tests="10" failures="1" timestamp="17 мар 2018 10:57:56 GMT" time="1.496" errors="0">
  <testcase name="CreateAndDeleteClientTest" time="0.029" classname="com.tsyrulik.dmitry.model.dao.impl.ClientDAOImplTest"/>
  <testcase name="updateClientTest" time="0.002" classname="com.tsyrulik.dmitry.model.dao.impl.ClientDAOImplTest"/>
  <testcase name="testCreateDeleteOrder" time="0.007" classname="com.tsyrulik.dmitry.model.dao.impl.OrderDAOImplTest">
    <failure type="com.tsyrulik.dmitry.model.exception.DAOFitnessException" message="com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column &amp;apos;number_of_lessons&amp;apos; in &amp;apos;field list&amp;apos;">
      <![CDATA[com.tsyrulik.dmitry.model.exception.DAOFitnessException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'number_of_lessons' in 'field list'
at com.tsyrulik.dmitry.model.dao.impl.OrderDAOImpl.createOrder(OrderDAOImpl.java:39)
at com.tsyrulik.dmitry.model.dao.impl.OrderDAOImplTest.testCreateDeleteOrder(OrderDAOImplTest.java:73)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'number_of_lessons' in 'field list'
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
at com.mysql.jdbc.Util.getInstance(Util.java:408)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
at com.tsyrulik.dmitry.model.dao.impl.OrderDAOImpl.createOrder(OrderDAOImpl.java:36)
... 36 more
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testCreateDeleteOrder -->
  <testcase name="createExercisesForClientTest" time="0.005" classname="com.tsyrulik.dmitry.model.dao.impl.TrainerDAOImplTest"/>
  <testcase name="testDeleteTrainer" time="0.023" classname="com.tsyrulik.dmitry.model.dao.impl.TrainerDAOImplTest"/>
  <testcase name="testUpdateTrainer" time="0.002" classname="com.tsyrulik.dmitry.model.dao.impl.TrainerDAOImplTest"/>
  <testcase name="createUser" time="0.004" classname="com.tsyrulik.dmitry.model.dao.impl.UserDAOImplTest"/>
  <testcase name="findUserByWrongUsernameOrPassword" time="0.002" classname="com.tsyrulik.dmitry.model.dao.impl.UserDAOImplTest"/>
  <testcase name="updateUserByUser" time="0.001" classname="com.tsyrulik.dmitry.model.dao.impl.UserDAOImplTest"/>
  <testcase name="shouldEncryptString" time="0.0" classname="com.tsyrulik.dmitry.model.util.MD5Test"/>
</testsuite> <!-- Command line test -->
